### PR TITLE
feat(processIssueComment): added Project Management

### PR DESCRIPTION
**Pull request by Berkmann18**
Added the PM category from all-contributors/all-contributors#199.

### CODE REVIEW

**Comment by jakebolam** [comment]
@Berkmann18 thanks 🙏 way to cover all the extra cases.

Looks like the snapshots may be outdated. May have to bump the version of `all-contributors-cli`

**Comment by Berkmann18** [comment]
Yeah, I just noticed the markdown bits in the snapshot, I'll update `all-contributors-cli` and update the snapshots in a few seconds.

**Comment by jakebolam** [comment]
@Berkmann18 I can't see any snapshots?

**Comment by Berkmann18** [comment]
@jakebolam On https://github.com/all-contributors/all-contributors-bot/pull/166/commits/9113d83b37050c4614d5d0a20f2cc691f9f93008?

**Comment by jakebolam** [comment]
Hmmm the changes aren't on the files tab? https://github.com/all-contributors/all-contributors-bot/pull/166/files

**Comment by Berkmann18** [comment]
@jakebolam How weird, it shows up on the commit file changes but once you remove the filter it doesn't.

**Comment by jakebolam** [comment]
@Berkmann18 the CI is failing due to lint https://github.com/all-contributors/all-contributors-bot/pull/166/checks?check_run_id=82301923

**Comment by Berkmann18** [comment]
Fixed.

**Comment by jakebolam** [comment]
Deploying: https://circleci.com/workflow-run/8311d3a3-5893-4775-a62a-9cf08efd5978

Once its deployed to the sandbox want to test it on https://github.com/all-contributors-sandbox/test-all-contributors/issues/1

**Pull request merged**
