### PR TITLE
fix: allow bot to respond to other bots too

### LINKED ISSUE #244: Does not respond to other bots' comments
Hi @jakebolam and other maintainers!

I have a question about how the All Contributors bot operates. 

Right now I am using [Ranger](https://reporanger.com) to create my All Contributor comments, as shown here: https://github.com/carbon-app/carbon/pull/858#issuecomment-531336464; however, the All Contributors bot doesn't respond. 

I assume this is because Ranger isn't an owner or something, but Ranger does have write access to this repo. 

In my opinion, Ranger should be treated almost equivalently to other maintainers, especially when they have the valid permissions. 

Really appreciate your time helping me understand this issue.

### PR DESCRIPTION
**Pull request by mfix22**
Closes #244

### CODE REVIEW

**Comment by CompuIves** [comment]
We would find this very useful for CodeSandbox as well!

**Comment by mfix22** [comment]
Thanks Ives! ❤️

**Comment by gr2m** [comment]
Shall we merge it or try to implement the todo tests first?

**Comment by mfix22** [comment]
@gr2m up to you. There is no loss in test quality, so I could update them in this PR or a follow up. I won’t be able to get to it until this Friday, however.

**Comment by gr2m** [comment]
yeah we can follow up

**Pull request merged**
