### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by pgrimaud**
Hi,

This tiny PR will fix : 

- 1 typo in `contributing/bot-architecture.md`
- 1 typo in `src/tasks/processIssueComment/utils/parse-comment/index.js`

Best! :robot:

### CODE REVIEW

**Comment by pgrimaud** [comment]
Hi @Berkmann18 

I updated my commit name.

**Comment by pgrimaud** [comment]
> Don't forget to also change the PR title as well (since that's what the master-based CI would look at 😉).

Woops sorry, I missed this one. PR name edited too 👍

**Comment by gr2m** [comment]
@Berkmann18 I'm checking in about your permissions, sorry for that!

**Comment by gr2m** [comment]
@Berkmann18 the setting was wrong for this repository, it's fixed now, very sorry!

**Pull request merged**
