### PR TITLE
upgrade all contributors cli to v6.9.1

### PR DESCRIPTION
**Pull request by ahonn**
resolve https://github.com/all-contributors/all-contributors-bot/issues/247

### CODE REVIEW

**Comment by protoEvangelion** [comment]
@jakebolam @Berkmann18 any chance we can get a green thumb on this? 👍

**Comment by protoEvangelion** [comment]
Thanks @Berkmann18 @gr2m 🎉

**Comment by protoEvangelion** [comment]
And thanks for the speedy work @ahonn !

**Comment by gr2m** [comment]
Can't make promises when I get to deploy this though, it's complicated :tm:

**Comment by protoEvangelion** [comment]
image

**Pull request merged**
