### PR TITLE
docs: improve local developer experience

### LINKED ISSUE #104: Improve development experience
**Is your feature request related to a problem? Please describe.**
Local development experience is currently confusing with probot and serverless runners. 

**Describe the solution you'd like**
Just use serverless:
- ~Run lambdas in serverless~ (see #86)
- ~Create a serverless plugin to allow use of smee proxy in development~  -> Now in #188 
- Document development experience 
- Remove `yarn start-probot`
- Update `yarn start` to use `yarn start-serverless`

### PR DESCRIPTION
**Pull request by jakebolam**
Closes #104

### CODE REVIEW

**Comment by jakebolam** [comment]
This is really light first attempt, and will need further review, just want to get a base in. Please open PRs to fix if you find issues with the docs

**Comment by jakebolam** [comment]
@Berkmann18 @sinchang I'd love to get your feedback on the document improvements for local development.

I merged this one, but if you comment on here about any issues I will do a follow up pull request.

**Comment by sinchang** [comment]
working on my local development, nice. 👍

**Comment by Berkmann18** [comment]
It kinda works well, only when I pass the payload from the comment I get in https://github.com/settings/apps/all-contributors-dev/advanced to Postman otherwise no comment from the bot even tho both GitHub and Smee logs the comments.

On top of that, I see `Error: octokit.authenticate() is deprecated. Use "auth" constructor option instead.` and I'm wondering if it only happens to me?

**Pull request merged**
