### PR TITLE
chore: upgraded several dependencies

### PR DESCRIPTION
**Pull request by Berkmann18**
Bump all (except `all-contributors-cli` which is upgraded in #124) dependencies.

### CODE REVIEW

**Comment by sinchang** [comment]
why greenkeeper not work? can we fix it?

**Comment by jakebolam** [comment]
Thanks @Berkmann18. I double checked and greenkeeper is enabled. Hmm

**Comment by Berkmann18** [comment]
@sinchang I don't know, normally it should have caught that and dealt with it but for some reason, it didn't and I use @dependabot on my repos so I'm not sure if it's a common situation.
@gr2m Any idea?

**Comment by gr2m** [comment]
Green keeper works for me. I think there was a recent outage, maybe reset the installation? You can do that at https://account.greenkeeper.io/

**Comment by Berkmann18** [comment]
@gr2m > you wouldn’t get Greenkeeper pull requests for the others.

Oh okay, good to know, so for in-range updates, @greenkeeper isn't able to deal with them compared to say @dependabot?

**Comment by gr2m** [comment]
Greenkeeper does deal with in-range updates. It creates branches in the background to trigger CI builds. If they fail, Greenkeeper will inform you that an in-range update of a dependency caused an error. But if the test passes you don’t usually need to know about it, at least for libraries that others install as a dependency. As this is an app with a lock file, you might want to receive all these updates, but depending on the amount of dependencies this can get quite noisy. You can simply pin the dependency versions (remove the `^`), so all updates will be out of range

**Comment by Berkmann18** [comment]
Okay, thanks for the information.

**Pull request merged**
