### PR TITLE
feat(processIssueComment): added 'data' contributors

### PR DESCRIPTION
**Pull request by smoia**
Implements the "Data" category from all-contributors/all-contributors#336
and all-contributors/all-contributors-cli#231.

Cfr. all-contributors/all-contributors#334.

Using #166 as model.

### CODE REVIEW

**Comment by smoia** [comment]
Hi all, any update on this? Do I need to do something more? I can't wait to use the bot for this contribution type!

**Comment by smoia** [comment]
Hi there!
Any update on this PR? I'd love to use it!

**Comment by Berkmann18** [comment]
Only someone in @all-contributors/core who has write permissions (so not me) would be able to approve this.

**Comment by jakebolam** [comment]
Thank you @smoia

**Comment by smoia** [comment]
Thank you @jakebolam for merging it in!
@Berkmann18 I think we can close also the original issue all-contributors/all-contributors#334!
is there any other step to do, or everything is done now?

**Comment by Berkmann18** [comment]
@smoia Yup.

**Pull request merged**
